#' Run PCA on Long-Format Data
#'
#' This function takes a long-format data frame, pivots it to a wide format,
#' and then performs Principal Component Analysis (PCA).
#'
#' @param data A data.frame with metabolite information - assumed to be generated by `process_runs` or `read_and_clean_data`
#' @param vbl Character defining the column of `data` to use for the PCA
#'
#' @return A `prcomp` object with the PCA results
#'
#' @importFrom tidyr pivot_wider
#' @importFrom stats prcomp
#' @export
run_pca <- function(data, vbl)
{
  mat <- data |>
    select(sample, metabolites, {{vbl}}) |>
    pivot_wider(names_from = metabolites, values_from = {{vbl}})

  samples <- mat$sample
  mat <- select(mat, -sample) |>
    as.matrix()
  rownames(mat) <- samples

  # Filter Zero Variance
  vars <- apply(mat, 2, var, na.rm=TRUE)
  mat <- mat[, vars > 0 & !is.na(vars), drop=FALSE]

  # return null if not enough variable columns exist
  if(ncol(mat) < 2) return(NULL) # Safety check

  # PCA
  retval <- prcomp(mat, center = TRUE, scale. = TRUE)

  return(retval)
}